import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Flix",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white text-gray-900`}>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
